version: 2
jobs:
  build:
    
    working_directory: ~/dako

    docker:
      - image: ubuntu:19.04

    steps:

      - checkout

      - run: apt-get update -qq
      - run: apt-get install -y gcc-8 g++-8 git default-jdk curl unzip zip

      - run:
          name: install vcpkg
          command: |            
            git clone https://github.com/Microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg integrate install
            ./vcpkg/vcpkg install restinio:x64-linux
            cd native
            mkdir build
            cmake .. -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make
            strip libdakota.so
            cp libdakota.so ../../src/main/resources/META-INF
            cd ..
            cd ..

      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/dakota-1.0.0-SNAPSHOT.jar
